import os
import matplotlib.pyplot as plt
import numpy as np

"""Script to sequentially plot raw oscilloscope waveforms generated by the capture script."""

SHOTS = 1

print("Starting sequential waveform plotting...")
print("Close the current plot window to load the next waveform.\n")

for i in range(SHOTS):
    filename = f"waveform00001.txt"

    if not os.path.exists(filename):
        print(f"Warning: {filename} not found. Skipping...")
        continue

    print(f"Displaying {filename}...")

    data = np.loadtxt(filename, skiprows=2, delimiter=",")

    time_data = data[:, 0]
    voltage_data = data[:, 1]

    plt.figure(figsize=(8, 4))

    plt.plot(time_data, voltage_data, color="royalblue", linewidth=1.5)

    plt.title(f"Oscilloscope Waveform - Shot {i+1:05d}", fontsize=12)
    plt.xlabel("Time (s)", fontsize=10)
    plt.ylabel("Voltage (V)", fontsize=10)
    plt.grid(True, linestyle="--", alpha=0.6)

    plt.tight_layout()

    plt.show()

    plt.close()

print("Finished displaying all waveforms.")